[project]
name = 'Blockchain-Interoperability-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.dimensional-bridge-nft]
path = 'contracts/dimensional-bridge-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.dimensional-translation]
path = 'contracts/dimensional-translation.clar'
clarity_version = 2
epoch = 2.5

[contracts.inter-dimensional-transactions]
path = 'contracts/inter-dimensional-transactions.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
