[project]
name = 'Blockchain-Interoperability-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-validation-consensus]
path = 'contracts/data-validation-consensus.clar'
clarity_version = 2
epoch = 2.5

[contracts.dimensional-bridge-nft]
path = 'contracts/dimensional-bridge-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
